"""added img_url portion to categories for prev

Revision ID: 4217b5563493
Revises: 9f113476f1a5
Create Date: 2022-01-23 17:06:38.945346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4217b5563493'
down_revision = '9f113476f1a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('img_url', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'img_url')
    # ### end Alembic commands ###
